import 'dart:io';
import 'dart:typed_data';

import 'package:image/image.dart' as img;
import 'package:path/path.dart' as p;
import 'package:qr_image_exporter/qr_image_exporter.dart';

import 'package:test/test.dart';

// Helper function to extract component values from a 32-bit ARGB color
int getR(int color) => (color >> 16) & 0xFF;
int getG(int color) => (color >> 8) & 0xFF;
int getB(int color) => color & 0xFF;
int getA(int color) => (color >> 24) & 0xFF;

void main() {
  group('QrImageExporter', () {
    late Directory testOutputDir;

    // Set up a temporary directory for test output files.
    setUp(() {
      final Directory currentDir = Directory.current;
      testOutputDir = Directory(p.join(currentDir.path, 'test_output'));
      if (!testOutputDir.existsSync()) {
        testOutputDir.createSync(recursive: true);
      }
    });

    // Clean up the temporary directory after all tests in this group have run.
    tearDown(() {
      if (testOutputDir.existsSync()) {
        testOutputDir.deleteSync(recursive: true);
      }
    });

    // Helper function to verify file integrity
    void verifyFileIntegrity(
      String testName,
      Uint8List pngBytes,
      Directory testOutputDir,
    ) {
      final String filePath = p.join(
        testOutputDir.path,
        'test_qrcode_$testName.png', // Incorporate the test name into the file name
      );

      File(filePath).writeAsBytesSync(pngBytes);

      final File outputFile = File(filePath);

      expect(
        outputFile.existsSync(),
        isTrue,
        reason: 'Output file must exist after writing.',
      );
      expect(
        outputFile.lengthSync(),
        equals(pngBytes.length),
        reason: 'File size must match generated bytes length.',
      );
    }

    // Basic Functionality Test
    test('should export a basic QR code to PNG bytes with default colors', () {
      // GIVEN: Set up QR data, image object, and calculate the expected size
      const String qrData = 'https://pub.dev/packages/qr';
      final QrCode qrCode = QrCode(
        payload: QrPayload.fromString(qrData),
        errorCorrectLevel: QrErrorCorrectLevel.medium,
      );
      final QrImage qrImage = QrImage(qrCode);

      const int moduleSize = 5;
      const int margin = 25;

      final int expectedSize =
          (qrImage.moduleCount * moduleSize) + (margin * 2);

      // WHEN: Generate PNG bytes and decode the resulting image
      final Uint8List? pngBytes = qrImage.toPngBytes(
        moduleSize: moduleSize,
        margin: margin,
      );

      // Decode the generated bytes back to an image for assertions.
      final img.Image? decodedImage = img.decodePng(pngBytes!);

      // THEN: Assert dimensions, basic output validity, and file integrity
      // 1. Basic output verification
      expect(pngBytes, isNotNull, reason: 'PNG bytes should be generated.');
      expect(
        pngBytes.isNotEmpty,
        isTrue,
        reason: 'PNG bytes should not be empty.',
      );
      expect(
        decodedImage,
        isNotNull,
        reason: 'Decoded image should not be null.',
      );

      // 2. Dimension verification
      expect(
        decodedImage!.width,
        equals(expectedSize),
        reason: 'Image width must match calculated size.',
      );
      expect(
        decodedImage.height,
        equals(expectedSize),
        reason: 'Image height must match calculated size.',
      );

      // 3. File output and integrity verification
      verifyFileIntegrity('basic', pngBytes, testOutputDir);
    });

    // Custom Colors and Sizes Test
    test('should handle different colors and sizes', () {
      // GIVEN: Set up QR data with custom colors and calculated expected size
      const String qrData = 'https://github.com/kevmoo/qr.dart';
      final QrCode qrCode = QrCode(
        payload: QrPayload.fromString(qrData),
        errorCorrectLevel: QrErrorCorrectLevel.low,
      );
      final QrImage qrImage = QrImage(qrCode);

      const int moduleSize = 2;
      const int margin = 10;
      const int darkColor = 0xFF0000FF; // Blue
      const int lightColor = 0xFFFFFF00; // Yellow

      final int expectedSize =
          (qrImage.moduleCount * moduleSize) + (margin * 2);

      // WHEN: Generate PNG bytes with custom options and decode
      final Uint8List? pngBytes = qrImage.toPngBytes(
        moduleSize: moduleSize,
        margin: margin,
        darkColor: darkColor,
        lightColor: lightColor,
      );

      // Decode the generated bytes back to an image for assertions.
      final img.Image? decodedImage = img.decodePng(pngBytes!);

      // THEN: Assert output validity, dimension accuracy, and file integrity
      // 1. Basic output verification
      expect(pngBytes, isNotNull);
      expect(pngBytes.isNotEmpty, isTrue);
      expect(decodedImage, isNotNull);

      // 2. Dimension verification
      expect(decodedImage!.width, equals(expectedSize));
      expect(decodedImage.height, equals(expectedSize));

      // 3. File output and integrity verification
      verifyFileIntegrity('custom_colors_sizes', pngBytes, testOutputDir);
    });

    // Empty Data Test
    test('should export an empty QR code (Version 1) to PNG bytes', () {
      // GIVEN: Set up an empty QR code (results in Version 1) and calculate expected size
      const String qrData = ''; // Empty string
      final QrCode qrCode = QrCode(
        payload: QrPayload.fromString(qrData),
        errorCorrectLevel: QrErrorCorrectLevel.medium,
      );
      final QrImage qrImage = QrImage(qrCode);

      const int moduleSize = 5;
      const int margin = 25;

      // Version 1 QR code has moduleCount = 21
      final int expectedSize =
          (qrImage.moduleCount * moduleSize) +
          (margin * 2); // 21 * 5 + 50 = 155

      // WHEN: Generate PNG bytes and decode the resulting image
      final Uint8List? pngBytes = qrImage.toPngBytes(
        moduleSize: moduleSize,
        margin: margin,
      );

      // Decode the generated bytes back to an image for assertions.
      final img.Image? decodedImage = img.decodePng(pngBytes!);

      // THEN: Assert output validity, dimension accuracy, and file integrity
      // 1. Basic output verification
      expect(pngBytes, isNotNull);
      expect(pngBytes.isNotEmpty, isTrue);
      expect(decodedImage, isNotNull);

      // 2. Dimension verification
      expect(decodedImage!.width, equals(expectedSize));
      expect(decodedImage.height, equals(expectedSize));

      // 3. File output and integrity verification
      verifyFileIntegrity('empty_data', pngBytes, testOutputDir);
    });

    // Color Verification Test
    test('should correctly apply dark and light colors at specific points', () {
      // GIVEN: Set up QR data and custom colors for pixel verification
      const String qrData = 'Color Test Data Verification';
      final QrCode qrCode = QrCode(
        payload: QrPayload.fromString(qrData),
        errorCorrectLevel: QrErrorCorrectLevel.high,
      );
      final QrImage qrImage = QrImage(qrCode);

      const int moduleSize = 8;
      const int margin = 16;
      const int customDarkColor = 0xFFCC0000; // Opaque Red
      const int customLightColor = 0xFF00FF00; // Opaque Green

      // WHEN: Generate PNG bytes and decode the resulting image
      final Uint8List? pngBytes = qrImage.toPngBytes(
        moduleSize: moduleSize,
        margin: margin,
        darkColor: customDarkColor,
        lightColor: customLightColor,
      );

      // Decode the generated bytes back to an image for assertions.
      final img.Image? decodedImage = img.decodePng(pngBytes!);

      // THEN: Assert pixel color components (R, G, B, A) at specific points, and file integrity
      expect(pngBytes, isNotNull);
      expect(decodedImage, isNotNull);

      // 1. Light module/Margin verification: top-left margin area
      const int marginPixelX = margin ~/ 2;
      const int marginPixelY = margin ~/ 2;
      final img.Pixel marginPixel = decodedImage!.getPixel(
        marginPixelX,
        marginPixelY,
      );

      // Assert margin pixel color matches the light color components
      expect(
        marginPixel.r.toInt(),
        equals(getR(customLightColor)),
        reason: 'Margin R mismatch',
      );
      expect(
        marginPixel.g.toInt(),
        equals(getG(customLightColor)),
        reason: 'Margin G mismatch',
      );
      expect(
        marginPixel.b.toInt(),
        equals(getB(customLightColor)),
        reason: 'Margin B mismatch',
      );
      expect(
        marginPixel.a.toInt(),
        equals(getA(customLightColor)),
        reason: 'Margin A mismatch',
      );

      // 2. Dark module verification: near the center of the top-left finder pattern
      const int moduleIndex = 3;
      const int darkPixelX =
          margin + (moduleIndex * moduleSize) + (moduleSize ~/ 2);
      const int darkPixelY =
          margin + (moduleIndex * moduleSize) + (moduleSize ~/ 2);
      final img.Pixel darkPixel = decodedImage.getPixel(darkPixelX, darkPixelY);

      // Assert dark module pixel color matches the dark color components
      expect(
        darkPixel.r.toInt(),
        equals(getR(customDarkColor)),
        reason: 'Dark R mismatch',
      );
      expect(
        darkPixel.g.toInt(),
        equals(getG(customDarkColor)),
        reason: 'Dark G mismatch',
      );
      expect(
        darkPixel.b.toInt(),
        equals(getB(customDarkColor)),
        reason: 'Dark B mismatch',
      );
      expect(
        darkPixel.a.toInt(),
        equals(getA(customDarkColor)),
        reason: 'Dark A mismatch',
      );

      // 3. File output and integrity verification
      verifyFileIntegrity('color_verification', pngBytes, testOutputDir);
    });

    // Zero Margin Test (Boundary Case)
    test('should correctly handle zero margin', () {
      // GIVEN: Set up QR data with zero margin and calculate expected size
      const String qrData = 'Zero Margin Test';
      final QrCode qrCode = QrCode(
        payload: QrPayload.fromString(qrData),
        errorCorrectLevel: QrErrorCorrectLevel.medium,
      );
      final QrImage qrImage = QrImage(qrCode);

      const int moduleSize = 4;
      const int margin = 0;

      final int expectedWidth = qrImage.moduleCount * moduleSize;

      // WHEN: Generate PNG bytes and decode the resulting image
      final Uint8List? pngBytes = qrImage.toPngBytes(
        moduleSize: moduleSize,
        margin: margin,
      );

      // Decode the generated bytes back to an image for assertions.
      final img.Image? decodedImage = img.decodePng(pngBytes!);

      // THEN: Assert dimensions, corner pixel color (dark module expected), and file integrity
      expect(pngBytes, isNotNull);
      expect(decodedImage, isNotNull);

      // 1. Dimension verification
      expect(decodedImage!.width, equals(expectedWidth));
      expect(decodedImage.height, equals(expectedWidth));

      // 2. Pixel verification: Corner pixel (0, 0) should be Dark (0xFF000000)
      final img.Pixel cornerPixel = decodedImage.getPixel(0, 0);

      expect(
        cornerPixel.r.toInt(),
        equals(0),
        reason: 'Corner R mismatch (should be dark)',
      );
      expect(
        cornerPixel.g.toInt(),
        equals(0),
        reason: 'Corner G mismatch (should be dark)',
      );
      expect(
        cornerPixel.b.toInt(),
        equals(0),
        reason: 'Corner B mismatch (should be dark)',
      );
      expect(
        cornerPixel.a.toInt(),
        equals(255),
        reason: 'Corner A mismatch (should be dark)',
      );

      // 3. File output and integrity verification
      verifyFileIntegrity('zero_margin', pngBytes, testOutputDir);
    });

    // Minimum Module Size Test (Boundary Case)
    test('should correctly handle minimum module size (1)', () {
      // GIVEN: Set up QR data with minimum module size (1) and calculate expected size
      const String qrData = 'Min Size Test';
      final QrCode qrCode = QrCode(
        payload: QrPayload.fromString(qrData),
        errorCorrectLevel: QrErrorCorrectLevel.medium,
      );
      final QrImage qrImage = QrImage(qrCode);

      const int moduleSize = 1;
      const int margin = 5;

      final int expectedWidth = qrImage.moduleCount + (margin * 2);

      // WHEN: Generate PNG bytes and decode the resulting image
      final Uint8List? pngBytes = qrImage.toPngBytes(
        moduleSize: moduleSize,
        margin: margin,
      );

      // Decode the generated bytes back to an image for assertions.
      final img.Image? decodedImage = img.decodePng(pngBytes!);

      // THEN: Assert output validity, dimension accuracy, and file integrity
      expect(pngBytes, isNotNull);
      expect(decodedImage, isNotNull);

      // 1. Dimension verification
      expect(decodedImage!.width, equals(expectedWidth));
      expect(decodedImage.height, equals(expectedWidth));

      // 2. File output and integrity verification
      verifyFileIntegrity('min_module_size', pngBytes, testOutputDir);
    });

    // Max Boundary Test (Version 40, largest possible QR code)
    test('should correctly handle max boundary QR code (Version 40)', () {
      // GIVEN: Set up max data for Version 40 (177 modules) and large parameters
      const int version40ModuleCount = 177; // Max module count for V40
      const int testDataLength = 1250;
      // Use a long string and high correction (H) to force V40
      final String qrData = 'X' * testDataLength;

      final QrCode qrCode = QrCode(
        payload: QrPayload.fromString(qrData),
        errorCorrectLevel: QrErrorCorrectLevel.high,
        minTypeNumber: 40,
      );
      final QrImage qrImage = QrImage(qrCode);

      const int moduleSize = 8;
      const int margin = 50;

      const int expectedSize =
          (version40ModuleCount * moduleSize) + (margin * 2);

      // WHEN: Generate PNG bytes for the maximum sized QR code and decode
      final Uint8List? pngBytes = qrImage.toPngBytes(
        moduleSize: moduleSize,
        margin: margin,
      );

      // Decode the generated bytes back to an image for assertions.
      final img.Image? decodedImage = img.decodePng(pngBytes!);

      // THEN: Assert module count, dimension accuracy, and file integrity
      expect(pngBytes, isNotNull);
      expect(decodedImage, isNotNull);

      // 1. Module Count Verification (Max Version 40)
      expect(
        qrImage.moduleCount,
        equals(version40ModuleCount),
        reason:
            'QR Code version should be 40 (177 modules) for max boundary test.',
      );

      // 2. Dimension verification
      expect(
        decodedImage!.width,
        equals(expectedSize),
        reason: 'Image width must match calculated size for V40.',
      );
      expect(
        decodedImage.height,
        equals(expectedSize),
        reason: 'Image height must match calculated size for V40.',
      );

      // 3. File output and integrity verification
      verifyFileIntegrity('max_boundary', pngBytes, testOutputDir);
    });

    // Invalid Geometric Bounds Test (Error Handling)
    test('should return null when invalid geometric bounds are provided', () {
      // GIVEN: Set up basic QR data
      const String qrData = 'Invalid Bounds Test';
      final QrCode qrCode = QrCode(
        payload: QrPayload.fromString(qrData),
        errorCorrectLevel: QrErrorCorrectLevel.medium,
      );
      final QrImage qrImage = QrImage(qrCode);

      // WHEN & THEN: Assert that invalid module sizes return null
      expect(
        qrImage.toPngBytes(moduleSize: 0, margin: 10),
        isNull,
        reason: 'moduleSize of 0 should return null',
      );
      expect(
        qrImage.toPngBytes(moduleSize: -5, margin: 10),
        isNull,
        reason: 'Negative moduleSize should return null',
      );

      // WHEN & THEN: Assert that invalid margins return null
      expect(
        qrImage.toPngBytes(moduleSize: 5, margin: -1),
        isNull,
        reason: 'Negative margin should return null',
      );
    });

    // OutOfMemory (OOM) Prevention Test (Boundary Case)
    test('should return null when requested image dimension exceeds max safe limit', () {
      // GIVEN: Set up basic QR data
      const String qrData = 'OOM Prevention Test';
      final QrCode qrCode = QrCode(
        payload: QrPayload.fromString(qrData),
        errorCorrectLevel: QrErrorCorrectLevel.medium,
      );
      final QrImage qrImage = QrImage(qrCode);

      // V1 QR code has 21 modules. 
      // If moduleSize is 200, width is 21 * 200 = 4200px.
      // 4200px > 4096px (maxSafeDimension), so it should be blocked.
      const int extremeModuleSize = 200;
      const int normalMargin = 0;

      // WHEN
      final Uint8List? pngBytesSizeOverflow = qrImage.toPngBytes(
        moduleSize: extremeModuleSize,
        margin: normalMargin,
      );

      // THEN: Assert that the massive image request is blocked and returns null
      expect(
        pngBytesSizeOverflow,
        isNull,
        reason: 'Image dimension exceeding 4096px should return null to prevent OOM.',
      );

      // GIVEN: Normal module size but massive margin
      // 21 * 10 = 210px. Margin of 2000 adds 4000px. Total = 4210px > 4096px.
      const int normalModuleSize = 10;
      const int extremeMargin = 2000;

      // WHEN
      final Uint8List? pngBytesMarginOverflow = qrImage.toPngBytes(
        moduleSize: normalModuleSize,
        margin: extremeMargin,
      );

      // THEN: Assert that the massive margin request is also blocked
      expect(
        pngBytesMarginOverflow,
        isNull,
        reason: 'Image dimension (due to extreme margin) exceeding 4096px should return null.',
      );
    });
  });
}
