# analysis_options.yaml
include: package:lints/recommended.yaml

linter:
  rules:
    - public_member_api_docs
    - always_specify_types
    - prefer_final_locals
    - prefer_const_constructors
    - avoid_print
    - unnecessary_this
    - prefer_single_quotes
    - sort_constructors_first
    - prefer_is_empty
    - avoid_returning_null_for_void
    - prefer_const_declarations
    - no_leading_underscores_for_local_identifiers
    - prefer_interpolation_to_compose_strings
    - unnecessary_string_interpolations
    - prefer_if_null_operators
    - require_trailing_commas
