name: Dart CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        sdk: [ '3.8.1', 'stable' ]

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Analyze code
        run: dart analyze

      - name: Run tests
        run: dart test